/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#ifndef CosNaming_H
#define CosNaming_H 1

/** TypeCode definitions */
/***************************/
#ifndef  TC_DEF_TC_CosNaming_NameComponent
#  define  TC_DEF_TC_CosNaming_NameComponent	1
#  ifdef __cplusplus
#    define  Defined_CosNaming_NameComponent	1
#  endif /* __cplusplus */
#endif
/***************************/
/***************************/
#ifndef  TC_DEF_TC_CORBA_sequence_CosNaming_NameComponent
#  define  TC_DEF_TC_CORBA_sequence_CosNaming_NameComponent	1
#  ifdef __cplusplus
#    define  Defined_CORBA_sequence_CosNaming_NameComponent	1
#  endif /* __cplusplus */
#endif
/***************************/
/***************************/
#ifndef  TC_DEF_TC_CosNaming_BindingType
#  define  TC_DEF_TC_CosNaming_BindingType	1
#  ifdef __cplusplus
#    define  Defined_CosNaming_BindingType	1
#  endif /* __cplusplus */
#endif
/***************************/
/***************************/
#ifndef  TC_DEF_TC_CosNaming_Binding
#  define  TC_DEF_TC_CosNaming_Binding	1
#  ifdef __cplusplus
#    define  Defined_CosNaming_Binding	1
#  endif /* __cplusplus */
#endif
/***************************/
/***************************/
#ifndef  TC_DEF_TC_CORBA_sequence_CosNaming_Binding
#  define  TC_DEF_TC_CORBA_sequence_CosNaming_Binding	1
#  ifdef __cplusplus
#    define  Defined_CORBA_sequence_CosNaming_Binding	1
#  endif /* __cplusplus */
#endif
/***************************/
/***************************/
#ifndef  TC_DEF_TC_CosNaming_NamingContext_NotFoundReason
#  define  TC_DEF_TC_CosNaming_NamingContext_NotFoundReason	1
#  ifdef __cplusplus
#    define  Defined_CosNaming_NamingContext_NotFoundReason	1
#  endif /* __cplusplus */
#endif
/***************************/
/***************************/
#ifndef  TC_DEF_TC_CosNaming_NamingContext_NotFound
#  define  TC_DEF_TC_CosNaming_NamingContext_NotFound	1
#  ifdef __cplusplus
#    define  Defined_CosNaming_NamingContext_NotFound	1
#  endif /* __cplusplus */
#endif
/***************************/
/***************************/
#ifndef  TC_DEF_TC_CosNaming_NamingContext_CannotProceed
#  define  TC_DEF_TC_CosNaming_NamingContext_CannotProceed	1
#  ifdef __cplusplus
#    define  Defined_CosNaming_NamingContext_CannotProceed	1
#  endif /* __cplusplus */
#endif
/***************************/
/***************************/
#ifndef  TC_DEF_TC_CosNaming_NamingContext_InvalidName
#  define  TC_DEF_TC_CosNaming_NamingContext_InvalidName	1
#  ifdef __cplusplus
#    define  Defined_CosNaming_NamingContext_InvalidName	1
#  endif /* __cplusplus */
#endif
/***************************/
/***************************/
#ifndef  TC_DEF_TC_CosNaming_NamingContext_AlreadyBound
#  define  TC_DEF_TC_CosNaming_NamingContext_AlreadyBound	1
#  ifdef __cplusplus
#    define  Defined_CosNaming_NamingContext_AlreadyBound	1
#  endif /* __cplusplus */
#endif
/***************************/
/***************************/
#ifndef  TC_DEF_TC_CosNaming_NamingContext_NotEmpty
#  define  TC_DEF_TC_CosNaming_NamingContext_NotEmpty	1
#  ifdef __cplusplus
#    define  Defined_CosNaming_NamingContext_NotEmpty	1
#  endif /* __cplusplus */
#endif
/***************************/
/***************************/
#ifndef  TC_DEF_TC_CosNaming_NamingContext
#  define  TC_DEF_TC_CosNaming_NamingContext	1
#  ifdef __cplusplus
#    define  Defined_CosNaming_NamingContext	1
#  endif /* __cplusplus */
#endif
/***************************/
/***************************/
#ifndef  TC_DEF_TC_CosNaming_BindingIterator
#  define  TC_DEF_TC_CosNaming_BindingIterator	1
#  ifdef __cplusplus
#    define  Defined_CosNaming_BindingIterator	1
#  endif /* __cplusplus */
#endif
/***************************/
/***************************/
#ifndef  TC_DEF_TC_CosNaming_NamingContextExt_InvalidAddress
#  define  TC_DEF_TC_CosNaming_NamingContextExt_InvalidAddress	1
#  ifdef __cplusplus
#    define  Defined_CosNaming_NamingContextExt_InvalidAddress	1
#  endif /* __cplusplus */
#endif
/***************************/
/***************************/
#ifndef  TC_DEF_TC_CosNaming_NamingContextExt
#  define  TC_DEF_TC_CosNaming_NamingContextExt	1
#  ifdef __cplusplus
#    define  Defined_CosNaming_NamingContextExt	1
#  endif /* __cplusplus */
#endif
/***************************/
#endif /*  CosNaming_H */
