/*
 * Copyright (c) 2008, AIST.
 * All rights reserved. This program is made available under the terms of the
 * Eclipse Public License v1.0 which accompanies this distribution, and is
 * available at http://www.eclipse.org/legal/epl-v10.html
 * Contributors:
 * National Institute of Advanced Industrial Science and Technology (AIST)
 */
/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#include "echo.h"

CORBA_string
Echo_echoString(CORBA_Echo _obj, const CORBA_char * mesg,
		CORBA_Environment * ev)
{
   CORBA_string _ORBIT_retval;
   void *_args[1];

   _args[0] = (void *) &mesg;
   invokeMethod(_obj, &Echo__imp.methods[0], (void **) &_ORBIT_retval, _args,
		ev);
   return _ORBIT_retval;
}

CORBA_string
Echo_echoString2(CORBA_Echo _obj, const CORBA_char * mesg, CORBA_string * res,
		 CORBA_Environment * ev)
{
   CORBA_string _ORBIT_retval;
   void *_args[2];

   _args[0] = (void *) &mesg;
   _args[1] = &res;
   invokeMethod(_obj, &Echo__imp.methods[1], (void **) &_ORBIT_retval, _args,
		ev);
   return _ORBIT_retval;
}

CORBA_string
Echo_echoString3(CORBA_Echo _obj, CORBA_string * mesg, CORBA_Environment * ev)
{
   CORBA_string _ORBIT_retval;
   void *_args[1];

   _args[0] = mesg;
   invokeMethod(_obj, &Echo__imp.methods[2], (void **) &_ORBIT_retval, _args,
		ev);
   return _ORBIT_retval;
}

CORBA_long
Echo_plus(CORBA_Echo _obj, const CORBA_long x, const CORBA_long y,
	  CORBA_Environment * ev)
{
   CORBA_long _ORBIT_retval;
   void *_args[2];

   _args[0] = (void *) &x;
   _args[1] = (void *) &y;
   invokeMethod(_obj, &Echo__imp.methods[3], (void **) &_ORBIT_retval, _args,
		ev);
   return _ORBIT_retval;
}

void
Echo_plus2(CORBA_Echo _obj, const CORBA_long x, const CORBA_long y,
	   CORBA_long * ans, CORBA_Environment * ev)
{
   void *_args[3];

   _args[0] = (void *) &x;
   _args[1] = (void *) &y;
   _args[2] = &ans;
   invokeMethod(_obj, &Echo__imp.methods[4], NULL, _args, ev);
}

CORBA_float
Echo_divide(CORBA_Echo _obj, const CORBA_float x, const CORBA_float y,
	    CORBA_Environment * ev)
{
   CORBA_float _ORBIT_retval;
   void *_args[2];

   _args[0] = (void *) &x;
   _args[1] = (void *) &y;
   invokeMethod(_obj, &Echo__imp.methods[5], (void **) &_ORBIT_retval, _args,
		ev);
   return _ORBIT_retval;
}

void
Echo_divide2(CORBA_Echo _obj, const CORBA_float x, const CORBA_float y,
	     CORBA_float * ans, CORBA_Environment * ev)
{
   void *_args[3];

   _args[0] = (void *) &x;
   _args[1] = (void *) &y;
   _args[2] = &ans;
   invokeMethod(_obj, &Echo__imp.methods[6], NULL, _args, ev);
}

#if __cplusplus
Echo_ptr Echo::_narrow(CORBA::Object_ptr obj)
{
  if (!obj)
    return Echo_ptr();

  return reinterpret_cast<Echo*>(obj.object());
}
CORBA_string Echo::echoString(const CORBA_char * mesg)
{
  return Echo_echoString(this->_impl, mesg, &this->ev);
}
CORBA_string Echo::echoString2(const CORBA_char * mesg, CORBA_string * res) {
  return Echo_echoString2(this->_impl, mesg, res, &this->ev);
}
CORBA_string Echo::echoString3(CORBA_string * mesg) {
  return Echo_echoString3(this->_impl, mesg, &this->ev);
}
CORBA_long Echo::plus(const CORBA_long x, const CORBA_long y) {
  return Echo_plus(this->_impl, x, y, &this->ev);
}
void Echo::plus2(const CORBA_long x, const CORBA_long y, CORBA_long * ans)
{
  Echo_plus2(this->_impl, x, y, ans, &this->ev);
  return;
}
CORBA_float Echo::divide(const CORBA_float x, const CORBA_float y) {
  return Echo_divide(this->_impl, x, y, &this->ev);
}
void
Echo::divide2(const CORBA_float x, const CORBA_float y,
	      CORBA_float * ans)
{
  Echo_divide2(this->_impl, x, y, ans, &this->ev);
  return;
}

#endif /// __cplusplus
