/*
 * Copyright (c) 2008, AIST.
 * All rights reserved. This program is made available under the terms of the
 * Eclipse Public License v1.0 which accompanies this distribution, and is
 * available at http://www.eclipse.org/legal/epl-v10.html
 * Contributors:
 * National Institute of Advanced Industrial Science and Technology (AIST)
 */
/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define echo_COMMON
#include "echo.h"

#ifndef ORBIT_IDL_C_IMODULE_echo
void
_RtORB_impl_Echo_echoString(CORBA_Echo obj, void **result,
			    CORBA_Class_Method * m, void **argv,
			    CORBA_Environment * env,
			    CORBA_string(*_impl_echoString)
			    (PortableServer_Servant _servant,
			     const CORBA_char * mesg, CORBA_Environment * ev))
{
   *(CORBA_string *) result =
      _impl_echoString(obj, *(const CORBA_char * *) argv[0], env);
}

void
_RtORB_impl_Echo_echoString2(CORBA_Echo obj, void **result,
			     CORBA_Class_Method * m, void **argv,
			     CORBA_Environment * env,
			     CORBA_string(*_impl_echoString2)
			     (PortableServer_Servant _servant,
			      const CORBA_char * mesg, CORBA_string * res,
			      CORBA_Environment * ev))
{
   *(CORBA_string *) result =
      _impl_echoString2(obj, *(const CORBA_char * *) argv[0],
			*(CORBA_string * *)argv[1], env);
}

void
_RtORB_impl_Echo_echoString3(CORBA_Echo obj, void **result,
			     CORBA_Class_Method * m, void **argv,
			     CORBA_Environment * env,
			     CORBA_string(*_impl_echoString3)
			     (PortableServer_Servant _servant,
			      CORBA_string * mesg, CORBA_Environment * ev))
{
   *(CORBA_string *) result =
      _impl_echoString3(obj, (CORBA_string *) argv[0], env);
}

void
_RtORB_impl_Echo_plus(CORBA_Echo obj, void **result, CORBA_Class_Method * m,
		      void **argv, CORBA_Environment * env,
		      CORBA_long(*_impl_plus) (PortableServer_Servant
					       _servant, const CORBA_long x,
					       const CORBA_long y,
					       CORBA_Environment * ev))
{
   *(CORBA_long *) result =
      _impl_plus(obj, *(const CORBA_long *) argv[0],
		 *(const CORBA_long *) argv[1], env);
}

void
_RtORB_impl_Echo_plus2(CORBA_Echo obj, void **result, CORBA_Class_Method * m,
		       void **argv, CORBA_Environment * env,
		       void (*_impl_plus2) (PortableServer_Servant _servant,
					    const CORBA_long x,
					    const CORBA_long y,
					    CORBA_long * ans,
					    CORBA_Environment * ev))
{
   _impl_plus2(obj, *(const CORBA_long *) argv[0],
	       *(const CORBA_long *) argv[1], *(CORBA_long * *)argv[2], env);
}

void
_RtORB_impl_Echo_divide(CORBA_Echo obj, void **result, CORBA_Class_Method * m,
			void **argv, CORBA_Environment * env,
			CORBA_float(*_impl_divide) (PortableServer_Servant
						    _servant,
						    const CORBA_float x,
						    const CORBA_float y,
						    CORBA_Environment * ev))
{
   *(CORBA_float *) result =
      _impl_divide(obj, *(const CORBA_float *) argv[0],
		   *(const CORBA_float *) argv[1], env);
}

void
_RtORB_impl_Echo_divide2(CORBA_Echo obj, void **result,
			 CORBA_Class_Method * m, void **argv,
			 CORBA_Environment * env,
			 void (*_impl_divide2) (PortableServer_Servant
						_servant, const CORBA_float x,
						const CORBA_float y,
						CORBA_float * ans,
						CORBA_Environment * ev))
{
   _impl_divide2(obj, *(const CORBA_float *) argv[0],
		 *(const CORBA_float *) argv[1], *(CORBA_float * *)argv[2],
		 env);
}

#endif
#if ( (TC_IMPL_TC_Echo_0 == 'e') \
&& (TC_IMPL_TC_Echo_1 == 'c') \
&& (TC_IMPL_TC_Echo_2 == 'h') \
&& (TC_IMPL_TC_Echo_3 == 'o') \
) && !defined(TC_DEF_TC_Echo)
#define TC_DEF_TC_Echo 1
/***   TC_Echo  ***/
#ifdef ORBIT_IDL_C_IMODULE_echo
static
#endif
const struct CORBA_TypeCode_struct TC_Echo_struct = {
   NULL,			// parent 
   tk_objref,			// kind 
   "IDL:Echo:1.0",		// repository_id 
   "Echo",			// identifier 
   0,				// member_count  
   NULL,			// member_name
   NULL,			// member_type
   NULL,			// member_label
   CORBA_OBJECT_NIL,		// discriminator  
   -1,				// default_index 
   0,				// length 
   NULL,			// content_type 
   0, 0,			// fixed_digits, fixed_scale 
   NULL,			// *member_visibility 
   NULL,			// type_modifier 
   NULL,			// *concrete_base_type 
   0,				// size
   0				// alignment
};
#endif

#ifndef ORBIT_IDL_C_IMODULE_echo
CORBA_unsigned_long Echo__classid = 0;
#endif

/* Interface type data */

static CORBA_IArg Echo_echoString__arginfo[] = {
   {TC_CORBA_string, CORBA_I_ARG_IN, "mesg"}
};
static CORBA_IArg Echo_echoString2__arginfo[] = {
   {TC_CORBA_string, CORBA_I_ARG_IN, "mesg"},
   {TC_CORBA_string, CORBA_I_ARG_OUT, "res"}
};
static CORBA_IArg Echo_echoString3__arginfo[] = {
   {TC_CORBA_string, CORBA_I_ARG_INOUT, "mesg"}
};
static CORBA_IArg Echo_plus__arginfo[] = {
   {TC_CORBA_long, CORBA_I_ARG_IN, "x"},
   {TC_CORBA_long, CORBA_I_ARG_IN, "y"}
};
static CORBA_IArg Echo_plus2__arginfo[] = {
   {TC_CORBA_long, CORBA_I_ARG_IN, "x"},
   {TC_CORBA_long, CORBA_I_ARG_IN, "y"},
   {TC_CORBA_long, CORBA_I_ARG_OUT, "ans"}
};
static CORBA_IArg Echo_divide__arginfo[] = {
   {TC_CORBA_float, CORBA_I_ARG_IN, "x"},
   {TC_CORBA_float, CORBA_I_ARG_IN, "y"}
};
static CORBA_IArg Echo_divide2__arginfo[] = {
   {TC_CORBA_float, CORBA_I_ARG_IN, "x"},
   {TC_CORBA_float, CORBA_I_ARG_IN, "y"},
   {TC_CORBA_float, CORBA_I_ARG_OUT, "ans"}
};

#ifdef ORBIT_IDL_C_IMODULE_echo
static
#endif
CORBA_Class_Method Echo__methods[] = {
   {
    "echoString",
    TC_CORBA_string,
    1, Echo_echoString__arginfo,
    0, NULL}
   , {
      "echoString2",
      TC_CORBA_string,
      2, Echo_echoString2__arginfo,
      0, NULL}
   , {
      "echoString3",
      TC_CORBA_string,
      1, Echo_echoString3__arginfo,
      0, NULL}
   , {
      "plus",
      TC_CORBA_long,
      2, Echo_plus__arginfo,
      0, NULL}
   , {
      "plus2",
      TC_void,
      3, Echo_plus2__arginfo,
      0, NULL}
   , {
      "divide",
      TC_CORBA_float,
      2, Echo_divide__arginfo,
      0, NULL}
   , {
      "divide2",
      TC_void,
      3, Echo_divide2__arginfo,
      0, NULL}
};
static char *Echo__base_itypes[] = {
   "IDL:omg.org/CORBA/Object:1.0"
};

#ifdef ORBIT_IDL_C_IMODULE_echo
static
#endif
CORBA_Class_Impl Echo__imp = {
   TC_Echo, "Echo", 7, Echo__methods,
   1, (char **) Echo__base_itypes
};
